services:
  kzt_map_controller:
    class: KatZoektThuis\MapBundle\Controller\MapController
    arguments:
      - "@security.token_storage"
      - "@router"
      - "@kat_zoekt_thuis_user_repository"
