services:
  kzt_map_menu_listener:
    class: KatZoektThuis\MapBundle\EventListener\MenuListener
    arguments:
      - "@security.authorization_checker"
      - "@security.token_storage"
    tags:
      - { name: kernel.event_listener, event: framework_core.configure_menu, method: onConfigureMenu }
