services:
  kat_zoekt_thuis_user_repository:
    class: KatZoektThuis\UserBundle\Repository\KatZoektThuisUserRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - KatZoektThuisUserBundle:KatZoektThuisUser

  veterinary_repository:
    class: KatZoektThuis\UserBundle\Repository\VeterinaryRepository
    factory: ["@doctrine.orm.default_entity_manager", getRepository]
    arguments:
      - KatZoektThuisUserBundle:Veterinary
